apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secrets
type: Opaque
data:
  # 실제 API 키를 base64로 인코딩한 값
  openai-api-key: c2stcHJvai05VUZ0TEc5WldndVZkWFVMNUR6bU9FQ0NHQXJKRGR6Z01GWS1JRHZ4NXh4eVhwSXBvdDdRODNCMDdVT0V1MzBQaHZkVzU2SEtWSlQzQmxia0ZKUmxTM3VwNGI2VkFnaVJtSnJZcUJad0FXeFFfWFd6Vnh0cVIwbEVHRzdqcFNlY3RsRzdHTG83QXFMR0FOa2h5clJ2eVVpWXBwc0E=
  perplexity-api-key: cHBseC1iZXBHM2VtUUFOcVUzZVU4V2VSSVZWYUN1TGRPOVZNNmU2VHk5bk5CMzhKaXdDWnA=
  flask-secret-key: c29tZS1yYW5kb20tc2VjcmV0LWtleQ== # "some-random-secret-key" encoded
